nelmio_api_doc:
    documentation:
        info:
            title:       « Mon API »
            description: « Documentation auto-générée »
            version:     « 1.0.0 »
    areas:
        default:
            path_patterns: [ '^/' ]
