# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    # 1) Encodage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2) Chargement des utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3) Configuration des firewalls
    firewalls:
        # Désactive la sécurité pour le profiler, assets, etc.
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal pour toute la partie /api
        main:
            pattern:   ^/api
            lazy:      true
            stateless: true
            provider:  app_user_provider

            # Votre authenticator perso pour les tokens API
            custom_authenticator: App\Security\ApiTokenAuthenticator

            # Activation du JSON login pour /api/login
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

    # 4) Règles d’accès
    access_control:
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/login,    roles: PUBLIC_ACCESS }
        - { path: ^/api/doc,      roles: PUBLIC_ACCESS }
        - { path: ^/api,          roles: ROLE_USER }

# 5) Overrides spécifiques à l’environnement “test”
when@test:
    security:
        # Ralentir moins le hasher pour accélérer les tests
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

        firewalls:
            main:
                # on réactive bien le même firewall “main” en test
                stateless: true
                json_login:
                    check_path: /api/login
                    username_path: email
                    password_path: password
