name: app

type: php:8.2

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_pgsql
        - pdo_mysql
        
relationships:
    database: "database:mysql"

variables:
    env:
        APP_ENV: prod
        APP_SECRET: '1fa3212a3d0728cc119673b61e16e0e5'
        DATABASE_URL: 'mysql://app:!ChangeMe!@database.internal:3306/app'

build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var/cache": { source: local, source_path: var/cache }
    
hooks:
    build: |
        set -x -e
        curl -fs https://get.symfony.com/cloud/configurator | bash
        NODE_VERSION=22 symfony-build

    deploy: |
        set -x -e
        symfony-deploy

crons:
    security-check:
        spec: '50 23 * * *'
        cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape COMPOSER_ROOT_VERSION=1.0.0 COMPOSER_AUDIT_ABANDONED=ignore composer audit --no-cache; fi
    clean-expired-sessions:
        spec: '17,47 * * * *'
        cmd: croncape php-session-clean
